name: CD
on:
  push:
    tags:
      - "*"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install libcurl-dev
        run: sudo apt install -y libcurl4-openssl-dev

      - name: Assemble
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble

      - name: Upload binary
        uses: svenstaro/upload-release-action@v2
        with:
          file: ${{ github.workspace }}/build/bin/native/tchimpReleaseExecutable/tchimp.kexe
          asset_name: tchimp
          overwrite: true
