name: CI
on: pull_request
jobs:
  linter-tests-assemble:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install libcurl-dev
        run: sudo apt install -y libcurl4-openssl-dev

      - name: Detekt
        uses: gradle/gradle-build-action@v3
        with:
          arguments: detekt

      - name: Kotlinter
        uses: gradle/gradle-build-action@v3
        with:
          arguments: lintKotlin

      - name: Unit tests
        uses: gradle/gradle-build-action@v3
        with:
          arguments: allTests

      - name: Assemble
        uses: gradle/gradle-build-action@v3
        with:
          arguments: assemble
