name: CI
on: pull_request
jobs:
  linter-tests-assemble:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Detekt
        uses: gradle/gradle-build-action@v2
        with:
          arguments: detektNativeMain detektNativeTest

      - name: Kotlinter
        uses: gradle/gradle-build-action@v2
        with:
          arguments: lintKotlinNativeMain lintKotlinNativeTest

      - name: Unit tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: nativeTest

      - name: Assemble
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble
