name: Pull request
on: pull_request
jobs:
  pull_request:
    runs-on: macos-13-xl
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Detekt + KtLint
        uses: gradle/gradle-build-action@v2
        with:
          arguments: detektNativeMain detektNativeTest ktlintCheck

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
