name: Pull request
on: pull_request
jobs:
  pull_request:
    runs-on: macos-13
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Detekt
        uses: gradle/gradle-build-action@v2
        with:
          arguments: detektNativeMain detektNativeTest

      - name: Kotlinter
        uses: gradle/gradle-build-action@v2
        with:
          arguments: lintKotlinNativeMain lintKotlinNativeTest

      - name: Unit tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: nativeTest

      - name: Compile
        uses: gradle/gradle-build-action@v2
        with:
          arguments: compileKotlinNative compileTestKotlinNative

      - name: Assemble
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble
